#!/usr/bin/env bash

set -euo pipefail

function usage {
    echo "Usage: $(basename "$0") ngrok|gcr"
    exit 1
}

[[ -v TELEGRAM_BOT_TOKEN ]] || (echo "TELEGRAM_BOT_TOKEN environment variable must be set" && exit 1)
[ -x "$(command -v ngrok)" ] || (echo "ngrok not installed" && exit 1)
[[ -v 1 ]] || usage

case "$1" in
  ngrok )
    url=$(curl -s http://localhost:4040/api/tunnels/command_line | jq -r '.public_url')
    echo "ngrok public URL: $url"
    ;;
  gcr )
    url="https://pakefte-malus-4rg55jdwva-uc.a.run.app"
    ;;
  *)
    usage
    ;;
esac

webhook_set=$(curl -s https://api.telegram.org/bot"$TELEGRAM_BOT_TOKEN"/setWebhook?url="$url" | jq -r '.ok')
webhook_url=$(curl -s https://api.telegram.org/bot"$TELEGRAM_BOT_TOKEN"/getWebhookInfo | jq -r '.result.url')
if [ "$webhook_set" == "true" ]; then
  echo "Webhook set to: $webhook_url"
else
  echo "Webhook not set, current webhook: $webhook_url"
  exit 1
fi
